import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { api } from "~/utils/api";

const Gallery: NextPage = () => {
  const images = api.image.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Image Gallery</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen bg-slate-800">
        <div className="container grid grid-cols-1 gap-4 py-12 px-4 mx-auto md:grid-cols-2 lg:grid-cols-3">
          {images.data?.map((image) => (
            <Image
              key={image.id}
              src={image.url}
              alt={image.id}
              width={300}
              height={200}
              className="object-cover rounded-lg"
            />
          ))}
        </div>
      </main>
    </>
  );
};

export default Gallery;
