import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import ImageUploader from "~/components/image-uploader";
import { env } from "~/env.mjs";
import axios from "axios";
import type { ImageType } from "react-images-uploading";
import { api } from "~/utils/api";

const {
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: cloud_name,
  NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET: upload_preset,
} = env;

const Home: NextPage = () => {
  const [images, setImages] = useState<ImageType[]>([]);
  const [uploadingLoader, setUploadingLoader] = useState(false);
  const createImage = api.image.create.useMutation();

  const handleUploadImages = () => {
    setUploadingLoader(true);
    images.map(async (image) => {
      const formData = new FormData();
      formData.append("file", image.file as File);
      formData.append("upload_preset", upload_preset);
      formData.append("cloud_name", cloud_name);
      formData.append("folder", "image_test");
      try {
        const res = await axios.post(
          `https://api.cloudinary.com/v1_1/${cloud_name}/image/upload`,
          formData
        );
        createImage.mutate({
          url: res.data.secure_url,
        });
      } catch (err) {
        console.error(err);
      } finally {
        setUploadingLoader(false);
        setImages([]);
      }
    });
  };

  return (
    <>
      <Head>
        <title>Image Uploader</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col gap-8 justify-center items-center h-screen bg-slate-800">
        <p className="text-2xl font-semibold text-slate-200">
          Please Upload Your Image...
        </p>
        <div className="container">
          <ImageUploader setImages={setImages} images={images} />
        </div>
        {uploadingLoader ? (
          <p className="font-semibold text-slate-200">Loading...</p>
        ) : (
          <button
            onClick={handleUploadImages}
            className="py-2 px-4 font-bold rounded-md border border-slate-200 text-slate-200 hover:bg-slate-200 hover:text-slate-800"
          >
            Upload
          </button>
        )}
      </main>
    </>
  );
};

export default Home;
